[package]
name = "zed-sidecar"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "k8s sidecar for zed-pkg."
repository = "https://github.com/zed-pkg/zed-sidecar.rs"
readme = "README.md"

[[bin]]
name = "zed-sidecar"
path = "src/main.rs"

[dependencies]
ores-otel-sidecar = { git = "https://github.com/ores-otel/ores-otel-sidecar.rs", rev = "3dc1c5bb2464e3f7f1776efc31d5b2ede60f1a84" }

[lints.rust]
unsafe_code = "forbid"
